from adaptive_quant.configuration import FrameworkConfig


CONFIG_4090 = FrameworkConfig(
    training_backend="pytorch",
    multi_hardware=True,
    dynamic_quant=True,
    learned_quant=True,
    quant_mode="hybrid",
    hardware_modes=("gpu", "cpu", "low_resource"),
    training_episodes=4096,
    evaluation_episodes=256,
    benchmark_training_episodes=1024,
    benchmark_evaluation_episodes=128,
    run_name="adaptive_universal_policy_torch4090",
    cache_prompt_features=True,
    log_every_n_episodes=8,
    torch_device="cuda",
    torch_dtype="bfloat16",
    torch_compile=True,
    torch_amp=True,
    torch_tf32=True,
    torch_hidden_dim=768,
    torch_mlp_depth=3,
    torch_learning_rate=3e-4,
    torch_weight_decay=1e-4,
    torch_batch_episodes=1024,
    torch_minibatch_size=512,
    torch_update_epochs=4,
    torch_ppo_clip=0.2,
    torch_value_coef=0.5,
    torch_entropy_coef=0.008,
    torch_max_grad_norm=1.0,
    torch_fused_optimizer=True,
    torch_preflight=True,
    torch_preflight_batch_size=8192,
    torch_preflight_warmup_steps=12,
    torch_preflight_steps=48,
    torch_preflight_min_free_memory_gb=10.0,
)
