"""Configuration schema (``FrameworkConfig``), reward weights, and validation helpers."""

from __future__ import annotations

from adaptive_quant.configuration.flat_access import config_to_flat_dict
from adaptive_quant.configuration.framework import FrameworkConfig, RewardWeights
from adaptive_quant.configuration.sections import (
    ArtifactPaths,
    LlamaCppSettings,
    MoESettings,
    OnlineSettings,
    RouterSettings,
    TorchSettings,
    TrainingSettings,
)
from adaptive_quant.configuration.validation import (
    MAX_EPISODE_COUNT,
    MAX_NUM_LAYERS,
    path_has_parent_reference,
    validate_artifact_dir,
    validate_backend,
    validate_bounded_positive_int,
    validate_cli_path_argument,
    validate_discrete_bit_widths,
    validate_env_sampling_mode,
    validate_hf_allowed_models,
    validate_llama_cpp_binary_allowlist,
    validate_moe_topology,
    validate_online_prompt_text,
    validate_optional_filesystem_path,
    validate_optional_hf_revision,
    validate_positive_int,
    validate_rl_train_policy_mode,
    validate_router_routes,
    validate_router_task_text,
    validate_run_name,
    validate_runtime_filesystem_path,
    validate_stability_probe_sampling,
    validate_structural_limits,
    validate_torch_policy_algorithm,
)

__all__ = [
    "ArtifactPaths",
    "FrameworkConfig",
    "LlamaCppSettings",
    "MoESettings",
    "OnlineSettings",
    "RewardWeights",
    "RouterSettings",
    "TorchSettings",
    "TrainingSettings",
    "config_to_flat_dict",
    "MAX_EPISODE_COUNT",
    "MAX_NUM_LAYERS",
    "path_has_parent_reference",
    "validate_artifact_dir",
    "validate_backend",
    "validate_bounded_positive_int",
    "validate_cli_path_argument",
    "validate_discrete_bit_widths",
    "validate_env_sampling_mode",
    "validate_hf_allowed_models",
    "validate_llama_cpp_binary_allowlist",
    "validate_moe_topology",
    "validate_optional_filesystem_path",
    "validate_optional_hf_revision",
    "validate_online_prompt_text",
    "validate_positive_int",
    "validate_router_task_text",
    "validate_rl_train_policy_mode",
    "validate_router_routes",
    "validate_run_name",
    "validate_runtime_filesystem_path",
    "validate_stability_probe_sampling",
    "validate_structural_limits",
    "validate_torch_policy_algorithm",
]
